### ISSUE TITLE
Possible bug? Not all posts being downloaded from an artist.

### ISSUE THREAD

**Issue by TheThirdComputer** [Jeffchen54/KMPDownloader#12]
Noticed when finishing downloading, that the amount of folders present in my logs is not the same with the ones being claimed to be present on kemono.party for a specific artist, here an example of how I did a test: 

E:\Programas_varios\-_P\KMP-Kemono-Downloader>KMPDownloader.py -d E:\Programas_varios\-_P\KMP-Kemono-Downloader\logs
03/14/2023 10:51:36 PM FOLDER -> E:\Programas_varios\-_P\KMP-Kemono-Downloader\logs\
03/14/2023 10:51:36 PM Please wait, scanning directory
03/14/2023 10:51:36 PM Finished scanning directory
Input a url, or type 'quit' to exit> https://kemono.party/patreon/user/574050

I tried both with '?o=0' and without it at the end of the url to check if it made a difference, but both end up giving a total amount of folders lesser than the total amount being claimed on kemono.party.

Example N2: 
Without being logged, using ?o=0 at the end of the url, instead of getting a total of 50 folders (posts) from kemono.party, it ends up with 47 (or a bit less) folders in my drive. I did a count of the files on kemono.party, and indeed there ARE a couple files which were not downloaded that I had to identify & download manually.

Any ideas? Thank you for your time.

EDIT-1: Version im using is v0.6.1.2-pre.
EDIT-2: A bit better in-deepth information.

**Comment by TheThirdComputer** [comment]
Version im using is v0.6.1.2-pre.

**Comment by Jeffchen54** [comment]
Okay the issue is Windows related. For some reason, a folder called DD and a folder called dd are the same even though the cases are different. Check the folder called "DD by berseepon from Patreon  Kemono (1)", you'll notice that there are 2 sets of photos in that folder. You'll probably see some other folders that end with () that have multiple other sets of photos in their folder. I wasn't aware that this was a thing in Windows but I don't think that it will be too difficult to account for Windows not being case sensitive for something where case should matter. I will look at providing a hotfix in the next few days if my schedule allows for it.

**Comment by TheThirdComputer** [comment]
I just noticed it after looking deeper into it, I should of noticed after you already said something similar on the last posted issue.

Still, thank you for the quick and efficient response.
