### ISSUE TITLE
An idea and/or request.

### ISSUE THREAD

**Issue by TheThirdComputer** [Jeffchen54/KMPDownloader#14]
Would you believe is possible to add the date in which a post was uploaded on kemono.party, at the start of a folder name after downloading it? 

Or maybe simply a number on front of the folder name based on post number or on other arbitrary decision.

This way to make the folders easier to differentiate, and maybe also deal with the issue of windows computer sharing files by folder name when the post also share exactly same name.

Again, thank you very much for all your efforts & time making this amazing piece of software, AND even more, considering is free.

EDIT-1: And, also remember no one is forcing you (at least I don't know, in such case, then please seek help), so please take your time on whatever you decide to do, on whenever you feel you are on the mood to do or not related to this idea or any other one. Cheers.

**Comment by Jeffchen54** [comment]
That's a great idea! I will consider adding this in the upcoming hotfix or a separate update soon.

Also, I'm not being forced to do this 🤣
I made this on the side to learn how to use Python and felt like Kemono would be a good site to tackle since there doesn't seem to be any definitive downloaders out there.

**Comment by Jeffchen54** [comment]
Added date switch in 0.6.2, thank you for you patience.
