### ISSUE TITLE
Maybe a bug in 0.4.2 (in zip files)

### ISSUE THREAD

**Issue by mario6714** [Jeffchen54/KMPDownloader#2]
Hi, i found this (the zip file don't have password), i hope this help, thanks.

C:\KMPDownloader>KMPDownloader -v -d C:\KMPDownloader\
INFO:root:UNZIP -> True
INFO:root:FOLDER -> C:\KMPDownloader\
Input a url, or type 'quit' to exit> https://kemono.party/patreon/user/7418131/post/67453965
CRITICAL:root:Unzipping a non zip file has occured or character limit for path has been reached or zip is password protected
 + File name: C:\KMPDownloader\sydusarts/JUNE ILLUSTRATIONS 2022 5.00 by sydusarts from Patreon  Kemono/Illustration 1 - Pekora Pyon.zip
File size: 16837538
INFO:root:Files downloaded: 0
INFO:root:0:00:11.297000

I compile to exe using this command "pyinstaller --onefile"

**Comment by Jeffchen54** [comment]
I have been having issues with pyinstaller creating an executable file, that is why the more recent releases lack any included executables. Does the same issue persist when you run the line using the .py file? I'm having trouble replicating the issue on my end. Knowing how finicky patool has been for me, it won't be surprising if it spits the error out for no reason.

The zip file should exists in the directory mentioned so you can extract it manually as well. 

EDIT:
I replicated the issue, right side is through pyinstaller --onefile and the left is the .py file. I will investigate what is causing this but the reason why I haven't used pyinstaller is mainly because of Cloudflare DDOS protection used by Kemono party.  The conversion to python to binary machine code isn't one to one, resulting in an essential library not functional as it is supposed to. I recommend sticking with the .py file and not using the pyinstaller, pyinstaller slows the program down anyway.
![image](https://user-images.githubusercontent.com/78765964/173248504-c83b9be1-22d8-4c0a-80cc-cd7f07fd9aa9.png)

**Comment by Jeffchen54** [comment]
Here's the reason why patoolib fails with pyinstaller:
![image](https://user-images.githubusercontent.com/78765964/173249064-4c06237c-e489-4fd1-bcee-fe87a36351a2.png)

Patoolib isn't being included, same issue with several other libraries. Use the .py file instead. I may be able to get the program working with pyinstaller; however, the benefit of pyinstaller is minuscule and possibly negative and the resources needed for compatibility are better allocated to somewhere else.

**Comment by mario6714** [comment]
Ok, so the problem is this "pyinstaller --onefile", thanks for check what is the problem, the KMPDownloader.py is working fine, thanks again.
