### ISSUE TITLE
Issues with switch '-w --date'

### ISSUE THREAD

**Issue by TheThirdComputer** [Jeffchen54/KMPDownloader#20]
Using version 0.6.2.

When downloading with the average command "Python KMPDownloader.py -d E:\Path", the files obtained show no problem.

But when using "Python KMPDownloader.py -w --date d E:\Path", on attempting to double-click open any obtained files an error pops up saying "directory name is invalid"... Technically, I can still open the files If I right click and use "open with... [software name]", but it becomes quite bothersome when you have to do so with over 100 files.

I will keep researching on the issue, and if I find any solutions, I will be updating it here. On the mean time, any ideas or possible solutions would be appreciated. Thank you~

**Comment by Jeffchen54** [comment]
That seems quite unusual, could you provide me any URLs you tried to download with the switch config?

**Comment by TheThirdComputer** [comment]
> That seems quite unusual, could you provide me any URLs you tried to download with the switch config?

Random test 1: https://kemono.party/fanbox/user/3231927
Random test 2: https://kemono.party/patreon/user/71224239

EDIT 1: I tried both with and without the switch, and it seems the switch produces the issue only.

It might have to do with the new 'Recommended (VENV)' of updating with 'install_requirements.bat'. Probably related to the virtual environment, tomorrow I will do a fresh-reset with the 'Unrecommended old approach' with the method of 'pip install -r requirements.txt' and see if that gives any results.

EDIT 2: I tried deleting the whole folders, but it gives a 'this element can not be found' error as if the folder did not exist. When copy-pasting or cutting the files from within the guilty folder into an average folder, the files now act normally. On the other hand, the switch-generated-folders keep giving the 'this element can not be found' error for any other kind of interaction with them (even as the folders are empty), moving & changing names & deleting the folders all giving this error. 
So, this information could narrow the problem as to how the folders are being generated being the issue.

**Comment by Jeffchen54** [comment]
Thanks for the info, issue has been fixed. It was caused by a buggy directory rename code and is available to be download from the releases now. 

NOTE: There might be a better way to delete the folders you encountered with the bug but the simplest way would be to open 7zip file manager and navigate to the directory and rename the folders 1 by 1. This will make the folders usable now and you can view or delete the folders. The issue was caused by a space at the end of the folder name which causes Windows to go haywire. There is nothing wrong with the installation method and this issue is due purely to a bug in folder naming. Sorry for any issues this may have caused.
