### ISSUE TITLE
Possible problem with discord, or?

### ISSUE THREAD

**Issue by TheThirdComputer** [Jeffchen54/KMPDownloader#34]
I have been attempting to download some artists discord, but, the software hangs after creating the containment folder, and then nothing happens. I thought that maybe I had to wait for the first .txt files which are light weight to be formed, but after 3 hours still nothing.

Is this normal? I don't remember it taking more than maybe half hour of 900kb of content in just empty folders & .txt files, and the one I'm downloading is rather small:

https://kemono.su/discord/server/960735840466763816

And yet after 1 hour nothing has been generated or downloaded visibly.

**Comment by Jeffchen54** [comment]
It sounds like the Discord API might have been changed, I'll take a look at what's going on and hopefully will have something for you by the end of this week.

**Comment by TheThirdComputer** [comment]
Unrelated question for when you update, or have free time.

Respect subscriberstar, do you have any knowledge as to why all posts are limited by around half of 2021? After checking several artists, they do keep updating as of present today thought, so I find it weird people stopped updating as of the year. And I have not been able to find any information on this, so I thought about asking you if maybe you know.

**Comment by Jeffchen54** [comment]
Sorry for the late response, have been a little busy as of late. I'm not sure the reason behind the outdated posts but it's possibly due to Kemono's scrapers not being updated to handle the site possibly due to new page format or API changes. Also, discord fixes are almost ready, quite a few api changes were made but luckily the code I have for discord isn't too hard-coded. It'll be out in a bit once I finish some more testing.

**Comment by Jeffchen54** [comment]
Issue should be fixed in the latest commit: https://github.com/Jeffchen54/KMP-Kemono-Downloader/tree/1e6f4c1f0bc9874761c03935f4252c50ed4f1539. You can just replace the DiscordToJson file with the updated one: [DiscordtoJson.py](https://github.com/Jeffchen54/KMP-Kemono-Downloader/blob/1e6f4c1f0bc9874761c03935f4252c50ed4f1539/DiscordtoJson.py) if you like. Hopefully it fixes everything but my Internet downloads half a megabyte a second so I wasn't able to do as much testing as I like within a reasonable amount of time.

**Comment by TheThirdComputer** [comment]
Sorry for the late response, was kinda busy until new year. I got to try the new updated DiscordtoJson.py file transition, and yes, it does work now. Thank you very much for the quick response Jeff, even if I was not able to respond as quick.

If I find any issues, I will be letting you know.
