### ISSUE TITLE
Maybe a bug in 0.4.2 and 0.5

### ISSUE THREAD

**Issue by mario6714** [Jeffchen54/KMPDownloader#4]
Here the log from cmd

  File "C:\Users\m\Downloads\KMPDownloader-main\KMPDownloader.py", line 141, in __download_file9M [00:00<?, ?iB/s]]
    with open(fname, 'wb') as fd, tqdm(                                                  | 0.00/47.1M [00:00<?, ?iB/s]]
OSError: [Errno 22] Invalid argument: 'C:\\Users\\m\\Downloads\\KMPDownloader\\HALkawa501/PSDChina Miku PSDClip Data by HALkawa501 from Patreon  Kemono/初音ミク94\x10x.clip'
                                                                                                                       Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Users\m\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\m\Downloads\KMPDownloader-main\Threadpool.py", line 228, in run
    todo[0](*todo[1])
  File "C:\Users\m\Downloads\KMPDownloader-main\KMPDownloader.py", line 141, in __download_file0<00:00, 8.39MiB/s]]
    with open(fname, 'wb') as fd, tqdm(
OSError: [Errno 22] Invalid argument: 'C:\\Users\\m\\Downloads\\KMPDownloader\\HALkawa501/PSDChina Miku PSDClip Data by HALkawa501 from Patreon  Kemono/初音ミク94\x10x.psd'

C:\Users\m\Downloads\KMPDownloader-main>KMPDownloader.py -t 12 -v -d C:\Users\m\Downloads\KMPDownloader\
INFO:root:THREAD_COUNT -> 12
INFO:root:UNZIP -> True
INFO:root:FOLDER -> C:\Users\m\Downloads\KMPDownloader\
Input a url, or type 'quit' to exit> https://kemono.party/patreon/user/38223307

**Comment by Jeffchen54** [comment]
Let me investigate this, are you using the latest release?

**Comment by Jeffchen54** [comment]
Might be one of the bugs that come from Kemono artist works not all being the same format, I'll fix this and have it up in the next release.

**Comment by mario6714** [comment]
Thanks

In this part "初音ミク" show some weird words in cmd:

OSError: [Errno 22] Invalid argument: 'C:\Users\m\Downloads\KMPDownloader\HALkawa501/PSDChina Miku PSDClip Data by HALkawa501 from Patreon Kemono/初音ミク94\x10x.clip'

here in github show this "初音ミク" instead a weird words

**Comment by Jeffchen54** [comment]
Issue fixed, if you noticed on Kemono, the download link looks like this:

Download 初音ミク94x.psd

The box symbol is interpreted as a '\\' and attempts to download to a nonexistent directory. Is fixed, seems like a very rare issue since not many creators use that symbol so I will bundle it with the next release instead of pushing an emergency release. 

For that issue you mentioned above, I noticed that when I run it on a fresh install of Windows but not on my main PC which displays the Japanese characters correctly.  I will take a look at it after I finish the release but its probably something related with Windows configurations or something.

**Comment by mario6714** [comment]
Thanks

**Comment by Jeffchen54** [comment]
I've fixed the issue on my fresh install of Windows, you should be able to follow the process in the following video: https://www.youtube.com/watch?v=bo52rBmTiT8

It involves tweaking a the locality setting on Windows to Japanese.
